### PR TITLE
Add folding

### PR DESCRIPTION
**Pull request by mxsdev**
This adds folding (aka nesting/collapsing/expanding). Demo:

[demo.webm](https://user-images.githubusercontent.com/16108792/176737279-c63f4cc6-5457-4d5e-8e52-acc5b0bde9c4.webm)

## Changes

- Options
  - **autofold_depth**: Depth past which symbols get folded by default. Set this to nil to disable the feature
  - **autounfold_hover**: Automatically unfolds hovered symbols
  - **fold_markers**: Markers to denote when something is folded/unfolded; setting to nil results in the same as before.
  - **only_reload_on_change**: Basically this enables diffing on the received lsp tree, more on this later.
- Hotkeys
  - Hotkeys for folding/unfolding as well as folding/unfolding all and resetting folds; see docs
 
## Diffing

To prevent the user's folds from being reset on an idempotent lsp update, I had to introduce some kind of diffing, which is just a basic dfs replacing only nodes (and their children) that are changed. It is also resistant to renaming, as it will only change the name if only the name is changed. This is implemented in `utils.merge_items_rec`.

Performance concerned users can opt-out of this by setting `only_reload_on_change` to false.

There may be finer methods of diffing by indexing nodes by their line numbers, but being resistant to idempotent operations and renames should cover most use cases.

## Other Notes

The plugin will rewrite the entire buffer on collapse/expand, which could significantly be improved by only deleting/inserting the necessary lines. Seeing as how the original rewrote the entire buffer on every lsp update, I assume this is fine :)

### CODE REVIEW

**Comment by simrat39** [comment]
Thanks for the PR! This looks really nice, would take me some time to look at the code but will definitely merge it. Sorry for getting to it so late

**Comment by mxsdev** [comment]
No problem! I've had the feature for myself so...I'm not complaining :p

Please let me know if you have any questions.

**Comment by simrat39** [comment]
Ok I've understood how most of the code works, I think its pretty clean, but I think we should also merge items automatically without an option. Also, would you be interested in rebasing this PR onto the new changes? A new PR is also fine because a lot of stuff has changed. If not, I can do it instead and amend you as the author, please let me know :+1:

**Comment by mxsdev** [comment]
Sounds good! Working on the rebase right now 👍

**Comment by mxsdev** [comment]
OK its rebased, although there's this bug with highlighting (Highlight start position inconsistent, sometimes the highlight color overrides the nesting indicator's color)

image

So idk what's causing that yet. Also, do you have a preference for where the highlighting should start? (at the picker, at the icon, at the field name)? I thought maybe just highlighting the field name would look the cleanest.

Oh yeah and, is there like a docgen tool for this project? I figure I'd ask before re-adding docs...

**Comment by simrat39** [comment]
> Also, do you have a preference for where the highlighting should start?

I think just the name being highlighted should look good

> Oh yeah and, is there like a docgen tool for this project? I figure I'd ask before re-adding docs...

Just update the readme for now, I plan on using https://github.com/kdheepak/panvimdoc to auto gen docs

**Comment by mxsdev** [comment]
Issue fixed and branch should now be good to merge :)

**Comment by simrat39** [comment]
Thanks, looks pretty good, I might move some stuff around but will get it merged by tonight or tomorrow. Again, thanks for the PR!

**Pull request merged**
