### PR TITLE
fix: initialize code_win to 0 instead of nil

### LINKED ISSUE #98: Quit file raise error [neovim nightly]
neovim version: NVIM v0.7.0-dev+823-g207307d0f
#### Step to reproduce
1. Open a directory using `nvim .`
2. Open file from filetree
3. Quit file using `:q`

#### Expected Behaviour 
Succesfully went to file tree

#### Error log
```
Error detected while processing WinEnter Autocommands for "*":                                                                                                                                                       
E5108: Error executing lua ...ged/symbols-outline.nvim/lua/symbols-outline/preview.lua:21: Expected Lua number                                                                                                       
stack traceback:                                                                                                                                                                                                     
        [C]: in function 'nvim_win_is_valid'                                                                                                                                                                         
        ...ged/symbols-outline.nvim/lua/symbols-outline/preview.lua:21: in function 'has_code_win'                                                                                                                   
        ...ged/symbols-outline.nvim/lua/symbols-outline/preview.lua:218: in function 'close'                                                                                                                         
        [string ":lua"]:1: in main chunk
```

* work fine with NVIM v.0.7.0-dev+812-g2f31e7b88

### PR DESCRIPTION
**Pull request by zeertzjq**
Ref <https://github.com/neovim/neovim/pull/16745>

Fix #98

### CODE REVIEW

**Comment by jemag** [comment]
Fixes #98

**Comment by yanzhang0219** [comment]
Please merge this @simrat39

**Comment by stark-zhang** [comment]
Merge it, please? this is a serious bug on nvim 0.7.0 @simrat39

**Comment by Sewdohe** [comment]
please merge 🙏

**Comment by yanzhang0219** [comment]
Discard this and switch to [aerial.nvim](https://github.com/stevearc/aerial.nvim). Hate myself I didn't find it earlier.

**Comment by Sewdohe** [comment]
> Discard this and switch to [aerial.nvim](https://github.com/stevearc/aerial.nvim). Hate myself I didn't find it earlier. 

Dude....thanks so much!!! That's an awesome plugin. I'm working on mimicking VS Code in Neovim and releasing an auto-installer for it you helped so much!

**Comment by yanzhang0219** [comment]
@Sewdohe You're welcome. Its unintuitive name makes it little known 😅

**Comment by Sewdohe** [comment]
> @Sewdohe You're welcome. Its unintuitive name makes it little known 😅

they definitely could've named it better. 

shoulda named it branches or something

**Comment by stark-zhang** [comment]
> Discard this and switch to [aerial.nvim](https://github.com/stevearc/aerial.nvim). Hate myself I didn't find it earlier.

Thanks a lot, I think it would be a better alternative plugin!

**Comment by simrat39** [comment]
sorry guys, had been really busy lately

**Pull request merged**
